#!/usr/bin/env bash
# Prints "Best School" 10 times; on 9th iteration prints "Best School" then "Hi"
i=1; while [ $i -le 10 ]; do if [ $i -eq 9 ]; then echo -e "Best School\nHi"; else echo "Best School"; fi; ((i++)); done
