#!/usr/bin/env bash
# Prints messages with special cases for 4th and 8th iteration using while and if-elif-else
i=1; while [ $i -le 10 ]; do if [ $i -eq 4 ]; then echo "bad luck"; elif [ $i -eq 8 ]; then echo "good luck"; else echo "Best School"; fi; ((i++)); done
