#!/usr/bin/env bash
# This script prints "To infinity and beyond" every 2 seconds and handles SIGTERM with a custom message

trap 'echo "I am invincible!!!"' SIGTERM

while true
do
  echo "To infinity and beyond"
  sleep 2
done
